repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        # additional_dependencies: ["black==25.1.0"]

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.7
    hooks:
      - id: pylint
        args: ["user_service/src/"]
        # additional_dependencies: ["pylint==3.3.7"]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.16.0
  #   hooks:
  #     - id: mypy
  #       args: ["user_service/src/"]
  #       # additional_dependencies: ["mypy==1.16.0"]
        