services:
  api:
    build: ./user_service/
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PRIVATE_KEY_PATH: /app/keys/private.pem
      PUBLIC_KEY_PATH: /app/keys/public.pem
      POSTGRES_USER: user_serv
      POSTGRES_PASS: 7ceb02b03d95ee9c
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: user_db
    volumes:
      - .:/app
      - ./keys:/app/keys:ro
    command: poetry run python -m uvicorn user_service.src.app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user_serv
      POSTGRES_PASSWORD: 7ceb02b03d95ee9c
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: