FROM python:3.13-slim

RUN apt-get update && apt-get install -y curl build-essential && \
    curl -sSL https://install.python-poetry.org | python3 - && \
    ln -s /root/.local/bin/poetry /usr/local/bin/poetry

WORKDIR /app

COPY pyproject.toml poetry.lock ./  
RUN pip install poetry && poetry config virtualenvs.create false && poetry install

COPY . .

CMD ["poetry", "run", "celery", "-A", "user_service.src.app.worker", "worker", "--loglevel=info"]
